name = "wwwmw-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Custom domain
routes = [
  { pattern = "wwwmw.captainpragmatic.com/*", zone_name = "captainpragmatic.com" }
]

# KV Namespaces for rate limiting
[[kv_namespaces]]
binding = "RATE_LIMITER"
id = "7df58aefa30f4310aac5a55e2e635801"

[vars]
ENVIRONMENT = "production"
